server:
  port: 9600
spring:
  rabbitmq:
    host: 192.168.2.160
    port: 5672
    username: ethan
    password: ethan
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    template:
      mandatory: true
    virtual-host: ethan